### ISSUE TITLE
Chrome in Windows 11

### ISSUE THREAD

**Issue by mar2357** [JacenBoy/ao3-blocker#2]
AO3-blocker isn't working in Chrome on Windows 11. It shows in the toolbar, when I click it, the dialog box isn't here. What am I doing wrong?

<img width="268" alt="Screenshot 2023-09-12 211126" src="https://github.com/JacenBoy/ao3-blocker/assets/73078322/676a20d0-6f4b-4eed-a22e-001306cc6fc2">

**Comment by JacenBoy** [comment]
What version of the script are you running? I just recently pushed an update to undo some breaking changed that GM_config introduced.

**Comment by JacenBoy** [comment]
I've just tweaked my update so it should have actually synced for GreasyFork now.

**Comment by mar2357** [comment]
It might have been the last remnants of McAfee's WebAdvisor interfering with the script. Once I manually deleted the files that "uninstall" left behind, it started working.

**Comment by JacenBoy** [comment]
Should be fixed more correctly as of [102869e](https://github.com/JacenBoy/ao3-blocker/commit/102869e872f97ed820c0886a3f013f08056fa696)
